version: '3'

services:
  frontend1:
    build: .
    container_name: frontend1
    environment:
      - NODE_ID=frontend1
    ports:
      - "3000:5173"
    networks:
      - frontend-network

  frontend2:
    build: .
    container_name: frontend2
    environment:
      - NODE_ID=frontend2
    ports:
      - "3001:5173"
    networks:
      - frontend-network

  frontend3:
    build: .
    container_name: frontend3
    environment:
      - NODE_ID=frontend3
    ports:
      - "3002:5173"
    networks:
      - frontend-network

  nginx:
    image: nginx:latest
    container_name: load_balancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend1
      - frontend2
      - frontend3
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
