version: '3'

services:
  frontend1:
    build:
      context: .
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_NODE_ID: frontend1
    container_name: frontend1
    ports:
      - "3000:4173"  # Vite preview runs on 4173
    networks:
      - frontend-network

  frontend2:
    build:
      context: .
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_NODE_ID: frontend2
    container_name: frontend2
    ports:
      - "3001:4173"
    networks:
      - frontend-network

  frontend3:
    build:
      context: .
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_NODE_ID: frontend3
    container_name: frontend3
    ports:
      - "3002:4173"
    networks:
      - frontend-network

  nginx:
    image: nginx:latest
    container_name: load_balancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend1
      - frontend2
      - frontend3
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
